-- Table: public.usuarios

-- DROP TABLE IF EXISTS public.usuarios;

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    action character varying(255) COLLATE pg_catalog."default",
    client_uuid character varying(255) COLLATE pg_catalog."default",
    local_date timestamp without time zone,
    response_code integer,
    response_description character varying(255) COLLATE pg_catalog."default",
    start_date timestamp without time zone,
    value double precision NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuarios
    OWNER to root;